language: node_js
cache:
  directories:
  - node_modules
before_script:
- npm run build
deploy:
  provider: firebase
  token:
    secure: gwajjGj9BuEyLPfV8fz/EnD17gfGB1anHd4Moa8e7fnUAteGRmyI58bUrEDUQXDrtKzElSaCP9w0t/RYBXbyRy2ebWmlt5yhNk1o4go1X7eiVL3kCf9Aak6FzDKFjdqPIdreO9TCZ3koE+hM+bK6Zs45LwJrFJ7CTCjerih4hBD3pwq5J2peCRHS7F5C/1x6isHvV0EOAqtPehHQfZtVufYak0Yg7/TuPBj5lTj30cSO3AoYECsuJp+eYR1L0Xtf+d46Ad8H0+lGTaCAwykZo47Hbfrv/wDAHJWfbWgm1PeoJq5P8Qv4O98s/IcI5TlHb9ryzqaeAMjCvqwzHSKawSo397opaIlpBXBhBISKinTLM/sD1qoZuOiJODBxPKQkwceU080plCBKPcWy5Q9yzp+IdbD6H7Sq1HvOXNm/YkhQGbHgbL2ULil1IOJ0ZHh3yYRhqWqkf1sFJigS95VUPT7C7OS/FTZkIKjPv5fvdAVkpORUpkFrwaNEbRmfJjELCTSxdzUPqmd8Lr9wyb4k+JgZZpryt4KMKLc/q3uLhWvuw/HpH3bO3TlP7vZTbf9tmBKuXvVxTxc/k2RDeDFE84kCZsxO1pKNT7hONgV3GVzovJGlbydjODZk/B5tfsekRut8Bjg2LQJ95poyLhsiP1mWq9BD+2Uj2vk/coSmPzc=
