language: node_js
cache:
  directories:
  - node_modules
before_script:
- npm run build
deploy:
  provider: firebase
  token:
    secure: D1bZ2oFZxmajRdCw41ciEU1hra7UD26JYBgSLCZX5/nP53Yz0p8DeLrppHfoUP3sDvWBvvcd5TXKz1UTzXinAri2D6k+9+2mG1NQySGM1GHp1BOktJIkLK5DoD/U0uTsWkwIzeXXeQ8QuYjzluvZF6HmpDoNLxAxbMvcAJWYwyamarUzFO+TzJ7SrN3o4VlChFfEtFcaNmeh6kjC4OoT2rtsIk4Jc+HVycmc4uiTtNVR9qjZ+mAJ0LjwvoDc96QL2xoyFqO8u5+78Dv6zEuruO9G9S5h6a2rkhw6ilUjFPF72CDfyxn3cRi3Z7xAvcSK3cMZnSeO8p01cvXBH656uUWvixHRtSJQ6KSOWFtUCiiFiYM9TrbK2DWp0zYkjW83C8aQRw7WdzDMCbh6SJDETuq3kdiGY8vobcERGYWEajNmOhQ4okMqvQB+cM9xaS4+eVVtdDZ1K9PN/uyIQXskrGSUFVOyjYsH7H3fj2nAddJ9GCDPGjyzNjXEyVMOmW7WBjZjxkqA+vFYKP/ynKKewXE+KkOC/kOEnQ6m7Zu6YjDEPrlhFpcIs0IOgO8V8vmfoGmaXKqoLYXuVYm862Rnk01ksp41DBpuirrC1LnZIXzgUBDPtkDAyfIdL8G4WrupRjDnJlxQ9esF7bdFafH9KjgO2kJmjbO+FtMtfFwQZ9I=
