language: node_js
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: KOnycUh+zj0cHu5WbYDYUc+4Fc9MXgGTb9xq3grg0IxPeUHAGK9nPYwTs1ZPefWe/bqAq3UvdBOeMrr4VilYTi1MeLNClgMOmFYZXMkUmG/qMfOBSe1r8b7RYP5Fu76x1NCfSTrcue222eVDBRf7+PQF+Dy8yw9YTqFZgawsgUYsCWC5txEQHZN7NMP3TLwTGugqfWobA8Suy+/YDS0TVmE7oCH90/IxFpHeOFOkArOJkrSvrVlYqdr5TWpLBstYUBtex3sXoOXCwl3wBHV7hnKtMABCihhY0M+XKYITuyxAe43wvLHT/F306Har69ng7qjAUXR/g1PM5babKY/fo74RmbZwjZLHmP5FCh7gbQxXotNEzX9z/0pv2jWY3VZsCYqtUYNkeKP8N9UsA84aK2Ijc56Sp057GBMbC6dcPWAtOx2dNrNg0BzgV9NvQQs1Y+Vdz5V1ih0A8CLGb4Qr0JQpnrKyK1LYKyYAH/wExJsWy3eF+OInlx+uTnrDPYPNHCOMy6ES2QrK9DcO5j6qs4qowQylY8WaTJo8MuFPhjJ8T15hyqUB4SqtAs5834p5gUiMJtwkbsT5jfoG09H2Xi7ab9ajt20A2CxL9WYkHPhoPO3U+YS33uIh83/kNLb1dm44hGAJyhMp19LiuBL0PvnmhpfW/9E0zdNN+J1gZHA=
