language: node_js
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: MLYmvyXnDUsx7iUXz248mosio6NUZcqV5cxEgIt2KESpMINLSP+EiUrIVnah8uL56bT0wzcDB2d9lA/kptLBb1xfyP5osLbdbcqnoTwoW1aVuvBdLgzcn98Rfefq17kvTDBUb9HkE5Fgswoy58KNEbBuBZvtarG5Ojx0UAoFEVv3nEY0OYLcxNnjXZGgl8vSenWkMlS+gNLrFRAZ3uBWYtZxMJB5vLv+joYD8/hwavMvNjsnHuF/TRU9QGY113llIoonD9mwyHxWVM7qNo5bKznf/sW5zl2+lSXMGAzZ6mXVGZEHm6MinMIr26LFGetAy91yw68aZ1n3YWOA+oHcz/0k6ViAWRCBtjwZ2n03V8rY08JtxxZrGMhk1X+g3rxR7TGlxZUP6reGw6t39RWD8LqjuccyuQpasRJK3Z627BkGDpWS9Lq6njhhYGjIe15h0iDBNVDUVN9/80sU3nZsKiRmFFve9aQrkuh58/tgjUbWJL7AFCrUGabH3MRJJI5pueUpOKIC7IrN0fafu3j4ckn3wZ0FpaSGfOJtZwsgWPyRnpRKVCYNRyBrPsr7U1ykavqtDJCXGquMdRganlVYyC5lkJqBD/OcGBqpEbICDC4vkG3qfC+34m8y86nu+r4vZ+PLKdbqu512vvWqvtj4h3eG58tZbf78uPZ7E3MfE8c=
