language: node_js
cache:
  directories:
  - node_modules
before_script:
- npm run build
deploy:
  provider: firebase
  token:
    secure: a1ukb0BTNqRxo3+mM1FTl+I1ShN0czhcpmnNCjMToYqbP/DAx+ShapYIzezCyxKf4wk2L+Pjo6feaxdLQmFt+9ICo0eC/r1Dqgh8U07ERp5L/jh9EqiaO16YAouG3SuyU3FcCPl+ZsRPyc2/Pl+yyROUpfwuOXfEDCdIe4DeXS8lRSjzYlKg3hFCxnkXQCBOoR5lC1tNxyvM2s2y+90lYtOpml5XTwhdw5yH3kqnneDtvK7Ot2SGkPH50fibHtsnOmvLYKzb8Cnt+kDyu2sRRpq5h9/aQvk3DVsWVlglMrJ0vFccuwCQp8xwsN0hDXac/2DhPzbsZdULXE3OOFjd5s+NwuDs4KVc0FQVPL96FJUMneYY5RsayP94BZWAsfROGRq70mNuuBqZctB0ikulfB6MAQRUP/eugCBcOa8BBnoHq1ozav2F2pKy52eK+hVR5BO39f8+42k/Zum7iH7xlnzbAFfNjeJHhVzpJ20Rh4C9sf4iZ0SDragFOysQ6PBiWy/yJfNQ9hnyWz7SOJjQZlNPU7aBgrjiD3APxtQQwARdv0u8GT7b9E0zIAYdmGX0qQAKd+FVsAviw32Gx+xNU14RgLK5Yik0Uf4zE/AilP+a1WqIQuPG/p1BG7kZw4ZNyKhFRr/FjHYAKF83gyj2Abh5ZtMGB14Kn8FvyOAmYe4=
