language: node_js
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  skip_cleanup: true
  edge: true
  provider: firebase
  token:
    secure: g6FqrPoIx1jqgtxKf1Bkir1YOWNNoRaSuBQMGDHZakN0K2rCqisnMeUjckcdR8SKvrFYHlIYOb7bW6LAj897SzvsFdEFArUYczUmUy788mORpHlwkBpfLuCWi8wDoCqxJOV1OIuU9umdwzjv1qURpTJTDU17Aa3OKZHLw3Y0lRAikMm7504mQV0VP8zHfCQGURPLC6gaPhLkSW50RVbozw4Rn56srxBEbYB2sbbiqOlJCvbPp2i1Ji2muZJO6P686W+JRDwjzMX/ZZ1fGNKhW+R6501FST2ZW1QVYT1X8f8T+LGZQGzoeU/qIvSwbQ9LlsQNli3mj1EpOs2fXPtGqEycqsBw1cVsM5lVp4XRmDrKPP8nVEK3Zsxaeq1u526oNudR4OM8EiDlQodic4ybXrQCZky5un0go/h1fE4Op2AwqdPZxYHNQm+leNMMfgTjxQlHaNoK9p4ZPw4n9qak+dt6P6lqdsAnLtEDItfKk2GtvRdBB70jPOFaHu1CTU+WhkKIIKdH2uwqGVm2zElSczxwcaTTl/lvmVmLin6tL6hljf0WBV+IlnHT3PjJTsLtB6A41Wmrj8iJQ5Niui4PRvrh1NUtbFon3pvtuumjW1VNGKT0FMFqBiVq1sVUUaEbGl6Nk4zpZPeXjg5lqZO98Xtglk60R0bz51ZYGIUr83I=
